using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Excessives.Unity;
using UnityEngine.InputSystem;

public class Board : MonoBehaviour
{
    [SerializeField] Rigidbody rb;

    [Tooltip("Thrust add to board when 'moving forward'")]
    [SerializeField]
    float thrust = 1.0f; // Thrust generated by the board (How is thrust generated?)

    [Tooltip("When turning board, apply this rotational force")]
    [SerializeField]
    float rotThrust = 1.0f;

    [SerializeField] InputAction cardinalInput;

    Vector2 Cardinal { get => cardinalInput.ReadValue<Vector2>(); }

    void OnEnable() { cardinalInput.Enable(); }

    void Start()
    {

    }

    void Update()
    {

        // Move board with keys at the start, use mouse to move camera

        // We are applying a force rather than direct velocity as it will also help when simulating
        // the difficulty of the board from going 'uphill' in the barrel.

        rb.AddForce(transform.forward * thrust * Mathf.Clamp01(Cardinal.y), ForceMode.Force);

        // With 'A', 'D' add rotational force
        // Would be nice to have an 'AddRelativeTorqueAtPoint' to add this torque from the board fins
        rb.AddRelativeTorque(Vector3.up * rotThrust * Cardinal.x, ForceMode.Force);
    }

    void OnDisable() { cardinalInput.Disable(); }
}
